김기완 blog/rss/github//linkedin추가
sarojaba/awesome-devblog pull request #412
Opened 2020-11-19 04:04 UTC by rldhks8745

김기완 blog/rss/github//linkedin추가

2020-11-19 04:06 UTC, rldhks8745 commented
소개글에 "awesome-devblog에 내 블로그 등록하기" 가 404뜨고 있어서 남들 등록하는 것 처럼 등록하였습니다... 감사합니다.

2020-11-19 05:22 UTC, sarojaba requested changes
linkedin 필드 대신 rocketpunch 필드로 수정 부탁드립니다.

2020-11-20 11:36 UTC, rldhks8745 commented
수정하였습니다! 감사합니다.

2020-11-21 00:05 UTC, merged

2020-11-21 00:05 UTC, sarojaba commented
감사합니다!