2021-04-04 Junhyunny's devlog blog add
sarojaba/awesome-devblog pull request #494
Opened 2021-04-04 14:15 UTC by Junhyunny

기술 블로그 추가 요청드립니다.

2021-04-04 16:08 UTC, sarojaba requested changes
블로그의 RSS도 함께 등록 부탁드립니다.

2021-04-05 11:54 UTC, Junhyunny commented
RSS 추가 등록하였습니다. 감사합니다.

2021-04-05 11:55 UTC, sarojaba approved these changes
수정 감사드립니다.

2021-04-05 11:55 UTC, merged

2021-04-05 11:55 UTC, sarojaba commented
감사합니다.