홍준혁 블로그 추가
sarojaba/awesome-devblog pull request #558
Opened 2021-09-07 05:46 UTC by Hong-JunHyeok

홍준혁 블로그 추가 부탁드립니다~

2021-09-07 15:19 UTC, sarojaba requested changes
불필요한 변경이 너무 많네요. 확인 부탁드립니다.

2021-09-08 02:08 UTC, Hong-JunHyeok commented
실수로 프리티어 설정을 해놔서 '이 "로 바뀌었나보네요...

2021-09-08 03:58 UTC, sarojaba approved these changes

2021-09-08 03:58 UTC, merged

2021-09-08 03:58 UTC, sarojaba commented
감사합니다.